{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "d5fa2a9c-93b3-4ccf-abb3-f3df7eed61ad",
   "metadata": {},
   "source": [
    "# Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "**Note: Here Exception class refers to the base class for all the exceptions.**"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2f140971-c6f4-428c-8c2a-7ce0e851fd3c",
   "metadata": {},
   "source": [
    "# Ans: 1\n",
    "When we create a custom exception in Python, it is important to inherit from the built-in 'Exception' class.\n",
    "\n",
    "- Here are a few reasons why:\n",
    "\n",
    "**Standard behavior:** The Exception class defines standard behaviors for exception objects, such as methods like str() and repr() that are used to convert an exception object to a string representation. When we inherit from the Exception class, our custom exception will automatically inherit these standard behaviors.\n",
    "\n",
    "**Exception hierarchy:** The Exception class is at the top of the exception hierarchy in Python, which means that all exceptions inherit from it. By inheriting from Exception, our custom exception becomes a part of this hierarchy and can be caught by any code that catches Exception or one of its subclasses.\n",
    "\n",
    "**Clear distinction:** By inheriting from Exception, our custom exception is clearly distinguished from other classes in our codebase. This makes it easier for developers to understand the purpose and behavior of our custom exception.\n",
    "\n",
    "**Compatibility:** Finally, inheriting from Exception ensures compatibility with other Python libraries and frameworks that expect exceptions to inherit from Exception. This can be important if our code needs to integrate with third-party libraries or if we want to share our code with others."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "286886cb-38c2-42ae-9dcc-736f2b3536bf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "eb6e7951-329c-4855-adb4-339c345fecd2",
   "metadata": {},
   "source": [
    "# Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "26fd8788-d0c0-41e7-980c-c0baf6254214",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "  Exception\n",
      "    TypeError\n",
      "      FloatOperation\n",
      "      MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "      ModuleNotFoundError\n",
      "      ZipImportError\n",
      "    OSError\n",
      "      ConnectionError\n",
      "        BrokenPipeError\n",
      "        ConnectionAbortedError\n",
      "        ConnectionRefusedError\n",
      "        ConnectionResetError\n",
      "          RemoteDisconnected\n",
      "      BlockingIOError\n",
      "      ChildProcessError\n",
      "      FileExistsError\n",
      "      FileNotFoundError\n",
      "      IsADirectoryError\n",
      "      NotADirectoryError\n",
      "      InterruptedError\n",
      "        InterruptedSystemCall\n",
      "      PermissionError\n",
      "      ProcessLookupError\n",
      "      TimeoutError\n",
      "      UnsupportedOperation\n",
      "      itimer_error\n",
      "      herror\n",
      "      gaierror\n",
      "      SSLError\n",
      "        SSLCertVerificationError\n",
      "        SSLZeroReturnError\n",
      "        SSLWantWriteError\n",
      "        SSLWantReadError\n",
      "        SSLSyscallError\n",
      "        SSLEOFError\n",
      "      Error\n",
      "        SameFileError\n",
      "      SpecialFileError\n",
      "      ExecError\n",
      "      ReadError\n",
      "      URLError\n",
      "        HTTPError\n",
      "        ContentTooShortError\n",
      "      BadGzipFile\n",
      "    EOFError\n",
      "      IncompleteReadError\n",
      "    RuntimeError\n",
      "      RecursionError\n",
      "      NotImplementedError\n",
      "        ZMQVersionError\n",
      "        StdinNotImplementedError\n",
      "      _DeadlockError\n",
      "      BrokenBarrierError\n",
      "      BrokenExecutor\n",
      "        BrokenThreadPool\n",
      "      SendfileNotAvailableError\n",
      "      ExtractionError\n",
      "      VariableError\n",
      "    NameError\n",
      "      UnboundLocalError\n",
      "    AttributeError\n",
      "      FrozenInstanceError\n",
      "    SyntaxError\n",
      "      IndentationError\n",
      "        TabError\n",
      "    LookupError\n",
      "      IndexError\n",
      "      KeyError\n",
      "        NoSuchKernel\n",
      "        UnknownBackend\n",
      "      CodecRegistryError\n",
      "    ValueError\n",
      "      UnicodeError\n",
      "        UnicodeEncodeError\n",
      "        UnicodeDecodeError\n",
      "        UnicodeTranslateError\n",
      "      UnsupportedOperation\n",
      "      JSONDecodeError\n",
      "      SSLCertVerificationError\n",
      "      Error\n",
      "      UnsupportedDigestmodError\n",
      "      IllegalMonthError\n",
      "      IllegalWeekdayError\n",
      "      ParserError\n",
      "      ClassNotFound\n",
      "      ClipboardEmpty\n",
      "      MessageDefect\n",
      "        NoBoundaryInMultipartDefect\n",
      "        StartBoundaryNotFoundDefect\n",
      "        CloseBoundaryNotFoundDefect\n",
      "        FirstHeaderLineIsContinuationDefect\n",
      "        MisplacedEnvelopeHeaderDefect\n",
      "        MissingHeaderBodySeparatorDefect\n",
      "        MultipartInvariantViolationDefect\n",
      "        InvalidMultipartContentTransferEncodingDefect\n",
      "        UndecodableBytesDefect\n",
      "        InvalidBase64PaddingDefect\n",
      "        InvalidBase64CharactersDefect\n",
      "        InvalidBase64LengthDefect\n",
      "        HeaderDefect\n",
      "          InvalidHeaderDefect\n",
      "          HeaderMissingRequiredValue\n",
      "          NonPrintableDefect\n",
      "          ObsoleteHeaderDefect\n",
      "          NonASCIILocalPartDefect\n",
      "          InvalidDateDefect\n",
      "      MacroToEdit\n",
      "      InvalidFileException\n",
      "      UnequalIterablesError\n",
      "      InvalidVersion\n",
      "      _InvalidELFFileHeader\n",
      "      InvalidWheelFilename\n",
      "      InvalidSdistFilename\n",
      "      InvalidSpecifier\n",
      "      InvalidMarker\n",
      "      UndefinedComparison\n",
      "      UndefinedEnvironmentName\n",
      "      InvalidRequirement\n",
      "        RequirementParseError\n",
      "      InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "      FloatingPointError\n",
      "      OverflowError\n",
      "      ZeroDivisionError\n",
      "        DivisionByZero\n",
      "        DivisionUndefined\n",
      "      DecimalException\n",
      "        Clamped\n",
      "        Rounded\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Inexact\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Subnormal\n",
      "          Underflow\n",
      "        DivisionByZero\n",
      "        FloatOperation\n",
      "        InvalidOperation\n",
      "          ConversionSyntax\n",
      "          DivisionImpossible\n",
      "          DivisionUndefined\n",
      "          InvalidContext\n",
      "    SystemError\n",
      "      CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "      UserWarning\n",
      "        GetPassWarning\n",
      "        FormatterWarning\n",
      "      EncodingWarning\n",
      "      DeprecationWarning\n",
      "        ProvisionalWarning\n",
      "      PendingDeprecationWarning\n",
      "      SyntaxWarning\n",
      "      RuntimeWarning\n",
      "        ProactorSelectorThreadWarning\n",
      "        UnknownTimezoneWarning\n",
      "        PEP440Warning\n",
      "      FutureWarning\n",
      "        ProvisionalCompleterWarning\n",
      "      ImportWarning\n",
      "      UnicodeWarning\n",
      "      BytesWarning\n",
      "      ResourceWarning\n",
      "      DeprecatedTzFormatWarning\n",
      "      PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "      CalledProcessError\n",
      "      TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "      CancelledError\n",
      "      TimeoutError\n",
      "      InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "      ZMQError\n",
      "        ContextTerminated\n",
      "        Again\n",
      "        InterruptedSystemCall\n",
      "      ZMQBindError\n",
      "      NotDone\n",
      "    PickleError\n",
      "      PicklingError\n",
      "      UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "      ConfigLoaderError\n",
      "        ArgumentError\n",
      "      ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "      MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "      NoSectionError\n",
      "      DuplicateSectionError\n",
      "      DuplicateOptionError\n",
      "      NoOptionError\n",
      "      InterpolationError\n",
      "        InterpolationMissingOptionError\n",
      "        InterpolationSyntaxError\n",
      "        InterpolationDepthError\n",
      "      ParsingError\n",
      "        MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "      EOF\n",
      "      TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "      TryNext\n",
      "      UsageError\n",
      "      StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "      InvalidAliasError\n",
      "    Error\n",
      "      InterfaceError\n",
      "      DatabaseError\n",
      "        InternalError\n",
      "        OperationalError\n",
      "        ProgrammingError\n",
      "        IntegrityError\n",
      "        DataError\n",
      "        NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "      IndexSizeErr\n",
      "      DomstringSizeErr\n",
      "      HierarchyRequestErr\n",
      "      WrongDocumentErr\n",
      "      InvalidCharacterErr\n",
      "      NoDataAllowedErr\n",
      "      NoModificationAllowedErr\n",
      "      NotFoundErr\n",
      "      NotSupportedErr\n",
      "      InuseAttributeErr\n",
      "      InvalidStateErr\n",
      "      SyntaxErr\n",
      "      InvalidModificationErr\n",
      "      NamespaceErr\n",
      "      InvalidAccessErr\n",
      "      ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "      InternalError\n",
      "      WrongVersion\n",
      "      RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "      MessageParseError\n",
      "        HeaderParseError\n",
      "        BoundaryError\n",
      "      MultipartConversionError\n",
      "      CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "      NotConnected\n",
      "      InvalidURL\n",
      "      UnknownProtocol\n",
      "      UnknownTransferEncoding\n",
      "      UnimplementedFileMode\n",
      "      IncompleteRead\n",
      "      ImproperConnectionState\n",
      "        CannotSendRequest\n",
      "        CannotSendHeader\n",
      "        ResponseNotReady\n",
      "      BadStatusLine\n",
      "        RemoteDisconnected\n",
      "      LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "      NoSuchProcess\n",
      "        ZombieProcess\n",
      "      AccessDenied\n",
      "      TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "      ProtocolError\n",
      "      ResponseError\n",
      "      Fault\n",
      "    ParseBaseException\n",
      "      ParseException\n",
      "      ParseFatalException\n",
      "        ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "      VersionConflict\n",
      "        ContextualVersionConflict\n",
      "      DistributionNotFound\n",
      "      UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n",
      "  GeneratorExit\n",
      "  SystemExit\n",
      "  KeyboardInterrupt\n",
      "  CancelledError\n",
      "  AbortThread\n"
     ]
    }
   ],
   "source": [
    "#Ans: 2\n",
    "\n",
    "import sys\n",
    "\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' '*indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent+2)\n",
    "\n",
    "print_exception_hierarchy(BaseException, indent=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9e07177a-b47e-43cd-b1e3-3b8813a7a633",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "fa9cecfd-7296-466f-9c63-1cbf7f23abf8",
   "metadata": {},
   "source": [
    "# Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2297fc85-c669-41a3-8f75-e798b648ee9b",
   "metadata": {},
   "source": [
    "# Ans: 3\n",
    "The ArithmeticError class is a subclass of the Exception class, and it is used to represent errors that occur during arithmetic operations in Python. Here are two examples of errors defined in the ArithmeticError class:\n",
    "\n",
    "**ZeroDivisionError:** This error is raised when you try to divide a number by zero."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "6c7daaf0-89f4-40ad-a8c5-5fd786d89e75",
   "metadata": {},
   "outputs": [],
   "source": [
    "#for example:\n",
    "\n",
    "import logging \n",
    "logging.basicConfig(filename = 'error.txt', level = logging.ERROR)\n",
    "\n",
    "try :\n",
    "    858/0\n",
    "    \n",
    "except ZeroDivisionError as e :\n",
    "    logging.error( 'ZeroDivisionError {}'.format(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41b729f9-96db-47d4-9827-e3b817fca0ad",
   "metadata": {},
   "source": [
    "**OverflowError:** This error is raised when a calculation produces a result that is too large to be represented as a standard Python integer."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b09891d2-4ccc-4e3e-9f2e-c39e0b1088d9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys \n",
    "\n",
    "max_int = sys.maxsize\n",
    "result = max_int * 2"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d6fde09b-e576-46b9-baf4-65cae374e39f",
   "metadata": {},
   "source": [
    "In both cases, the operation being performed is an arithmetic operation (division and multiplication, respectively), and both result in errors that are specific to arithmetic operations. By defining these errors as subclasses of ArithmeticError, Python provides a consistent way to handle arithmetic errors that can occur in many different contexts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8f9d65c1-fc1d-471c-a2ac-910c7643a1f4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "e0a6f2ed-8d31-46b6-b2ac-0133a70f2764",
   "metadata": {},
   "source": [
    "# Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5857d32c-91f1-4533-b66a-7b6a57a6b4d4",
   "metadata": {},
   "source": [
    "# Ans: 4\n",
    "he LookupError class is a subclass of the Exception class in Python, and it is used to represent errors that occur when a lookup or search operation fails to find a requested item or value.\n",
    "\n",
    "In general, lookup operations involve searching for a specific piece of information in a collection or database, and they can fail for a variety of reasons. Some common reasons why a lookup operation might fail include:\n",
    "\n",
    "The requested item or value does not exist in the collection or database. The search criteria are not specific enough to locate a unique item or value. The collection or database is not available or cannot be accessed. By defining a separate LookupError class to represent these types of errors, Python provides a consistent and standardized way for programmers to handle lookup errors in their code.\n",
    "\n",
    "**KeyError:** KeyError is raised when a key is not found in a dictionary. Dictionaries in Python are implemented as hash tables, which means that each key is hashed to a unique value that corresponds to its location in the dictionary. When you try to access a key that does not exist in a dictionary, a KeyError exception is raised"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "b7100e93-136e-427f-89cf-fec63810e2af",
   "metadata": {},
   "outputs": [],
   "source": [
    "#example of KeyKeyError:\n",
    "\n",
    "try :\n",
    "    d = {'key1' : 'Sudhanshu sir locker' , 'password' : [2,3,4,5]}\n",
    "    print(d[34])\n",
    "    \n",
    "except KeyError as e :\n",
    "    logging.error( \"'34' is not in the dictionary {}\".format(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0f565c0a-34cf-4221-9873-0544509a32f9",
   "metadata": {},
   "source": [
    "**IndexError:** IndexError is raised when you try to access an index that is out of range in a sequence (e.g., list or tuple). In Python, the indices of a sequence start at 0 and go up to the length of the sequence minus one. When you try to access an index that is outside this range, an IndexError exception is raised"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "2228f02a-6e4c-49e4-b454-f8cec3ba12d0",
   "metadata": {},
   "outputs": [],
   "source": [
    "#example of IndexError:\n",
    "try :\n",
    "    my_list = [12,13,14,15]\n",
    "    print(my_list[90])\n",
    "    \n",
    "except IndexError as e :\n",
    "    logging.error('list index out of range {}'.format(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a147afbc-3e94-46cf-bfde-57e1ac64facd",
   "metadata": {},
   "source": [
    "In both cases, these exceptions are raised when we try to access an element or a key that does not exist in a collection, and they provide a way for our code to gracefully handle these situations and prevent unexpected crashes or bugs."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c5f01cd1-8edc-4b2c-adc3-af3d0cb75e7f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "e5fa3aef-d430-4b27-a024-c2c2de74ec71",
   "metadata": {},
   "source": [
    "# Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e7a97003-210c-4af1-8362-d6e141404a7a",
   "metadata": {},
   "source": [
    "# Ans: 5\n",
    "**ImportError:** ImportError is an exception in Python that is raised when there is an error in importing a module. This exception can be raised for various reasons such as the module being missing, or the module being present but inaccessible or corrupt."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "026d6efb-23b1-4ffa-a2a2-e3bcac9e7965",
   "metadata": {},
   "outputs": [],
   "source": [
    "#example of ImpoImportError:\n",
    " # trying to import a missing module\n",
    "try:\n",
    "    import krishna_kumar\n",
    "except ImportError as e :\n",
    "    logging.error('The required module is missing! {}'.format(e))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2d22990b-954f-4140-a9b3-3aa50fc4f78d",
   "metadata": {},
   "source": [
    "**ModuleNotFoundError:**  ModuleNotFoundError is a Python error that occurs when the interpreter cannot find a module that it needs to import in order to execute the program. This error occurs when you try to import a module that doesn't exist in the Python environment or it can't be found in the system path."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "a91af0f4-2527-4e5c-92eb-e76b6eb3a6a5",
   "metadata": {},
   "outputs": [],
   "source": [
    "#example of ModuleNotFoundError :\n",
    "\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError as e:\n",
    "    logging.error(\"The 'non_existent_module' module does not exist! {}\".format(e))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cc4db423-8e77-4ad8-8923-2cfce5b19874",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "b2eec31c-be8e-4eb8-948f-db1003782216",
   "metadata": {},
   "source": [
    "# Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e4957166-6857-47f5-8329-45c88461f232",
   "metadata": {},
   "source": [
    "# Ans: 6\n",
    "- Here are some best practices for exception handling in Python:\n",
    "\n",
    "**Use try-except blocks judiciously:** Try-except blocks should be used only for exceptions that are known and expected. It is not recommended to use try-except blocks to catch all exceptions unless there is a compelling reason to do so.\n",
    "\n",
    "**Be specific about the exceptions you catch:** It is recommended to catch specific exceptions rather than catching all exceptions. This helps in writing more precise and understandable code.\n",
    "\n",
    "**Handle exceptions at the appropriate level:** Exceptions should be handled at the appropriate level in the code. For example, if an exception occurs in a function, it should be handled within the function rather than being passed up to the calling function.\n",
    "\n",
    "**Don't suppress exceptions:** It is not recommended to suppress exceptions without proper handling. This can lead to hard-to-debug issues and make the code harder to maintain.\n",
    "\n",
    "**Use finally blocks for cleanup:** The finally block is executed regardless of whether an exception is thrown or not. This makes it useful for cleaning up resources such as files or database connections.\n",
    "\n",
    "**Log exceptions:** Logging exceptions is a good practice as it helps in debugging and understanding the behavior of the code. It is recommended to use a logging framework such as the built-in logging module.\n",
    "\n",
    "**Raise exceptions when appropriate:** If an error condition is detected, it is recommended to raise an appropriate exception rather than returning an error code or printing an error message. This helps in making the code more robust and easier to maintain.\n",
    "\n",
    "**Use context managers:** Context managers are a useful way to ensure that resources are properly acquired and released. They are especially useful for handling exceptions that occur during resource acquisition or release.\n",
    "\n",
    "**Be consistent with exception handling style:** It is important to be consistent with exception handling style throughout the codebase. This makes the code easier to read and understand."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "31823b93-456a-4dab-9416-92323ee331a7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f53eca11-34b6-422b-9a02-37d50ebf3efe",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f8bc8961-9ec6-4f1e-8329-f5bc9e22a153",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
